// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBab2LnTV7C8aRw4pV6nt216coLrxAfQ9k',
    appId: '1:350683427754:android:6cb984a0c86a0167ef71d3',
    messagingSenderId: '350683427754',
    projectId: 'geetaxi-1025a',
    databaseURL: 'https://geetaxi-1025a-default-rtdb.firebaseio.com',
    storageBucket: 'geetaxi-1025a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYhWYR_OXkF40p1w8qS_F0vUHsHLkTwxQ',
    appId: '1:350683427754:ios:79bb6ebcd95ac8f9ef71d3',
    messagingSenderId: '350683427754',
    projectId: 'geetaxi-1025a',
    databaseURL: 'https://geetaxi-1025a-default-rtdb.firebaseio.com',
    storageBucket: 'geetaxi-1025a.appspot.com',
    iosBundleId: 'com.example.cabRider',
  );
}
